// Generated by CoffeeScript 1.8.0
(function() {
  var split;

  split = require('split');

  module.exports = function(process, _arg) {
    var prefix;
    prefix = _arg.prefix;
    process.stdout.pipe(split()).on('data', function(line) {
      return console.log(prefix, line);
    });
    return process.stderr.pipe(split()).on('data', function(line) {
      return console.error(prefix, line);
    });
  };

}).call(this);
